apiVersion: v1
kind: Secret
metadata:
  name: k8s-demo-secrets
  namespace: default
type: Opaque
stringData:
  application.yml: |
    app:
      secret:
        api-key: "my-secret-api-key-12345"
        db-password: "super-secret-password"
